version: '3'
services:
    frontend:
        build: ./Frontend
        ports: 
            - "5000:5000"
        depends_on:
            - mysql-server

    movies:
        build: ./MoviesQueryCommand
        ports: 
            - "8001:8001"
        depends_on:
            - mysql-server
    
    theatres:
        build: ./TheatresQueryCOmmand
        ports: 
            - "8002:8002"
        depends_on:
            - mysql-server

    payments:
        build: ./PaymentsQueryCommand
        ports: 
            - "8003:8003"
        depends_on:
            - mysql-server
            
    user:
        build: ./UserQueryCommand
        ports: 
            - "8004:8004"
        depends_on:
            - mysql-server

    mysql-server:
        build: ./MySqlServer
        # environment:
        #     - MYSQL_ROOT_PASSWORD=root@123
        # command: mysql -uroot -p'root@123' < MySqlServer/Basedata-MTB.sql 
        ports: 
            - "9000:3306"
        
